name: Awesome Calculator CI build

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Python environment
    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: 3.7

    # Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Run Unit Tests
    - name: Run Unit Tests and generate coverage report
      run: |
        cd src
        python -m unittest discover -s calculator/tests
        coverage run -m unittest discover -s calculator/tests
        coverage report
        coverage html

    # Archive code coverage HTML report
    - name: Upload code coverage HTML report
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: src/htmlcov

    # Create the Python package
    - name: Build Python package
      run: |
        cd src
        python -m build

    # Verify and list package output
    - name: Verify package creation
      run: |
        ls -la src/dist

    # Test installation of the package
    - name: Install the built package
      run: |
        pip install src/dist/*.whl

    # Archive the built package
    - name: Upload Python package artifacts
      uses: actions/upload-artifact@v4
      with:
        name: awesome-calculator-package
        path: src/dist/*.whl
