name: Awesome Calculator CI Build

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        cd src
        python -m pip install --upgrade pip
        pip install coverage
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Run Unit Tests and generate coverage report
      run: |
        cd src
        python -m unittest discover -s tests
        coverage run -m unittest discover -s tests
        coverage report
        coverage html

    - name: Archive code coverage HTML report
      uses: actions/upload-artifact@v3
      with:
        name: code-coverage-report
        path: src/htmlcov

    - name: Build Python package
      run: |
        cd src
        python -m pip install --user --upgrade build
        python -m build

    - name: Archive built package
      uses: actions/upload-artifact@v3
      with:
        name: awesome-calculator
        path: src/dist

  install-package:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.7
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'

    - name: Download built package
      uses: actions/download-artifact@v3
      with:
        name: awesome-calculator

    - name: Debug dist directory contents
      run: |
        ls -l src/dist

    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install src/dist/*.whl
